// 262 realistic inputs for name matching (venues typed with and without their city, artists, lists), each with
// the answer a reasonable person expects. Built by an independent review that ran them through ten versions
// of the matcher; every one of these was right in at least one version, and all are right now.
export default async function ({ place, art, runVenue, runArtist, runSplit, is, starts, eqList }) {
  const P = place;
  // ---------- venues ----------
  const pickIs = (name, city) => (o) => o.startsWith(`${name}${city ? ` [${city}]` : ""} `) && !o.startsWith(`${name}${city ? ` [${city}]` : ""} ambiguous`) ? true : o.startsWith(`${name}${city ? ` [${city}]` : ""} `);
  const exactIs = (name, city) => is(`${name}${city ? ` [${city}]` : ""} exact`);
  const notExactWrong = (name, city) => (o) => o.startsWith(`${name}${city ? ` [${city}]` : ""} `);

  // From the suite (sanity of the harness)
  const bowery = () => [P("Resorts World New York City", "New York", "New York", ["Casino", "Bar"]), P("New York City Center", undefined, undefined, ["Performing arts theater"]), P("The Bowery Ballroom", "New York", "New York")];
  await runVenue("Bowery Ballroom New York City", bowery(), exactIs("The Bowery Ballroom", "New York"), "suite");
  await runVenue("Bowery Ballroom, NYC", bowery(), exactIs("The Bowery Ballroom", "New York"));
  await runVenue("Bowery Ballroom, New York, NY", bowery(), exactIs("The Bowery Ballroom", "New York"));
  await runVenue("Bowery Ballroom, Manhattan", bowery(), notExactWrong("The Bowery Ballroom", "New York"), "borough typed, record filed New York");
  await runVenue("The Bowery Ballroom", bowery(), exactIs("The Bowery Ballroom", "New York"));
  await runVenue("Bowery Balroom, NYC", bowery(), notExactWrong("The Bowery Ballroom", "New York"), "typo");
  await runVenue("Bowery", bowery(), notExactWrong("The Bowery Ballroom", "New York"), "partial");
  const bow2 = () => [P("The Bowery Electric", "New York", "New York", ["Bar", "Live music venue"]), P("The Bowery Ballroom", "New York", "New York")];
  await runVenue("Bowery Electric", bow2(), exactIs("The Bowery Electric", "New York"));
  await runVenue("Bowery Ballroom", bow2(), exactIs("The Bowery Ballroom", "New York"));
  // Brooklyn
  await runVenue("Baby's All Right, Brooklyn", [P("Baby's All Right", "New York", "New York", ["Bar", "Live music venue"])], notExactWrong("Baby's All Right", "New York"), "if Qloo files Brooklyn as New York");
  await runVenue("Baby's All Right, Brooklyn", [P("Baby's All Right", "Brooklyn", "New York", ["Bar", "Live music venue"])], exactIs("Baby's All Right", "Brooklyn"));
  await runVenue("Babys All Right NYC", [P("Baby's All Right", "Brooklyn", "New York", ["Bar", "Live music venue"])], exactIs("Baby's All Right", "Brooklyn"));
  const bowls = () => [P("Brooklyn Bowl", "Brooklyn", "New York"), P("Brooklyn Bowl Las Vegas", "Las Vegas", "Nevada"), P("Brooklyn Bowl Nashville", "Nashville", "Tennessee"), P("Brooklyn Bowl Philadelphia", "Philadelphia", "Pennsylvania")];
  await runVenue("Brooklyn Bowl, Brooklyn", bowls(), exactIs("Brooklyn Bowl", "Brooklyn"));
  await runVenue("Brooklyn Bowl, Philly", bowls(), exactIs("Brooklyn Bowl Philadelphia", "Philadelphia"));
  await runVenue("Brooklyn Bowl Nashville", bowls(), exactIs("Brooklyn Bowl Nashville", "Nashville"));
  await runVenue("Brooklyn Bowl, Nashville, TN", bowls(), exactIs("Brooklyn Bowl Nashville", "Nashville"));
  await runVenue("Brooklyn Bowl Vegas", bowls(), exactIs("Brooklyn Bowl Las Vegas", "Las Vegas"));
  await runVenue("Brooklyn Bowl", bowls(), (o) => o.startsWith("Brooklyn Bowl"), "any Brooklyn Bowl");
  await runVenue("Music Hall of Williamsburg, Brooklyn", [P("The Music Hall", "Portsmouth", "New Hampshire", ["Concert hall"]), P("Music Hall of Williamsburg", "Brooklyn", "New York")], exactIs("Music Hall of Williamsburg", "Brooklyn"));
  await runVenue("Music Hall, Portsmouth NH", [P("Music Hall of Williamsburg", "Brooklyn", "New York"), P("The Music Hall", "Portsmouth", "New Hampshire", ["Concert hall"])], exactIs("The Music Hall", "Portsmouth"));
  await runVenue("Portsmouth Music Hall", [P("Music Hall of Williamsburg", "Brooklyn", "New York"), P("The Music Hall", "Portsmouth", "New Hampshire", ["Concert hall"])], exactIs("The Music Hall", "Portsmouth"));

  // Records with no city, typed with a city, and a weaker room in that city
  await runVenue("Lincoln Hall, Chicago", [P("The Lincoln Lodge", "Chicago", "Illinois", ["Comedy club"]), P("Lincoln Hall")], notExactWrong("Lincoln Hall"), "record with no city");
  await runVenue("Lincoln Hall, Chicago", [P("Lincoln Hall"), P("The Lincoln Lodge", "Chicago", "Illinois", ["Comedy club"])], notExactWrong("Lincoln Hall"), "record with no city, first");
  await runVenue("Cobra Lounge, Chicago", [P("Cobra Lounge"), P("Cobra Bar", "Chicago", "Illinois", ["Bar"])], notExactWrong("Cobra Lounge"), "record with no city");
  await runVenue("Thalia Hall, Chicago", [P("Thalia Hall"), P("Chicago Theatre", "Chicago", "Illinois", ["Performing arts theater"])], notExactWrong("Thalia Hall"));
  await runVenue("Thalia Hall, Chicago, IL", [P("Thalia Hall"), P("Thalia Bar", "Chicago", "Illinois", ["Bar"])], notExactWrong("Thalia Hall"));
  await runVenue("Mercury Lounge, New York", [P("Mercury Bar", "New York", "New York", ["Bar"]), P("Mercury Lounge")], notExactWrong("Mercury Lounge"));
  await runVenue("House of Blues, Chicago", [P("House of Blues Chicago"), P("House of Blues Houston", "Houston", "Texas")], exactIs("House of Blues Chicago"), "suite");
  await runVenue("Empty Bottle, Chicago", [P("The Empty Bottle")], notExactWrong("The Empty Bottle"));

  // Room filed in a suburb, typed with the metro city
  const rr = () => [P("Red Rocks Amphitheatre", "Morrison", "Colorado", ["Amphitheater"]), P("Red Rocks Bar", "Denver", "Colorado", ["Bar"])];
  const rrRev = () => [P("Red Rocks Bar", "Denver", "Colorado", ["Bar"]), P("Red Rocks Amphitheatre", "Morrison", "Colorado", ["Amphitheater"])];
  await runVenue("Red Rocks Amphitheatre, Denver", rr(), notExactWrong("Red Rocks Amphitheatre", "Morrison"), "full name typed, suburb");
  await runVenue("Red Rocks Amphitheater, Denver, CO", rrRev(), notExactWrong("Red Rocks Amphitheatre", "Morrison"), "full name typed, suburb");
  await runVenue("Red Rocks Amphitheatre Denver", [P("Red Rocks Amphitheatre", "Morrison", "Colorado", ["Amphitheater"]), P("Rock Bar", "Denver", "Colorado", ["Bar"])], notExactWrong("Red Rocks Amphitheatre", "Morrison"), "Rock Bar ~ rocks");
  await runVenue("Red Rocks Amphitheatre, Denver", [P("Red Lion", "Denver", "Colorado", ["Bar", "Pub"]), P("Red Rocks Amphitheatre", "Morrison", "Colorado", ["Amphitheater"])], notExactWrong("Red Rocks Amphitheatre", "Morrison"), "Red Lion shares 'red'");
  await runVenue("Red Rocks, Denver", rr(), notExactWrong("Red Rocks Amphitheatre", "Morrison"), "common shorthand");
  await runVenue("Red Rocks, Morrison CO", rr(), exactIs("Red Rocks Amphitheatre", "Morrison"));
  await runVenue("Red Rocks", rr(), notExactWrong("Red Rocks Amphitheatre", "Morrison"));
  const trb = () => [P("Los Angeles Theatre", "Los Angeles", "California", ["Performing arts theater"]), P("The Troubadour", "West Hollywood", "California")];
  await runVenue("Troubadour, Los Angeles", trb(), notExactWrong("The Troubadour", "West Hollywood"));
  await runVenue("Troubadour, West Hollywood", trb(), exactIs("The Troubadour", "West Hollywood"));
  await runVenue("The Troubadour, West Hollywood, CA", trb(), exactIs("The Troubadour", "West Hollywood"));
  await runVenue("Troubadour, LA", trb(), notExactWrong("The Troubadour", "West Hollywood"));
  await runVenue("Troubadour, West Hollywood", [P("The Troubadour", "Los Angeles", "California")], notExactWrong("The Troubadour", "Los Angeles"), "Qloo files it LA");
  await runVenue("Whisky a Go Go, Los Angeles", [P("Whisky a Go Go", "West Hollywood", "California", ["Night club"]), P("The Whisky Bar", "Los Angeles", "California", ["Bar"])], notExactWrong("Whisky a Go Go", "West Hollywood"));
  const cc = () => [P("Cat's Cradle Back Room", "Carrboro", "North Carolina"), P("Cat's Cradle", "Carrboro", "North Carolina"), P("Local 506", "Chapel Hill", "North Carolina", ["Bar", "Live music venue"])];
  await runVenue("Cat's Cradle, Chapel Hill", cc(), notExactWrong("Cat's Cradle", "Carrboro"));
  await runVenue("Cats Cradle Carrboro NC", cc(), exactIs("Cat's Cradle", "Carrboro"));
  await runVenue("Cat's Cradle Back Room", cc(), exactIs("Cat's Cradle Back Room", "Carrboro"));
  await runVenue("The Sinclair, Boston", [P("The Sinclair", "Cambridge", "Massachusetts"), P("Sinclair Bar", "Boston", "Massachusetts", ["Bar"])], notExactWrong("The Sinclair", "Cambridge"));
  await runVenue("Turf Club, Minneapolis", [P("Turf Club", "Saint Paul", "Minnesota"), P("Turf Bar", "Minneapolis", "Minnesota", ["Bar"])], notExactWrong("Turf Club", "Saint Paul"));
  await runVenue("Turf Club, St. Paul", [P("Turf Club", "Saint Paul", "Minnesota")], notExactWrong("Turf Club", "Saint Paul"));
  await runVenue("The Pageant, St. Louis", [P("The Pageant", "St. Louis", "Missouri")], exactIs("The Pageant", "St. Louis"));
  await runVenue("The Pageant, Saint Louis, MO", [P("The Pageant", "St. Louis", "Missouri")], notExactWrong("The Pageant", "St. Louis"));
  const fillDC = () => [P("The Fillmore", "Detroit", "Michigan"), P("The Fillmore Silver Spring", "Silver Spring", "Maryland"), P("The Fillmore", "San Francisco", "California")];
  await runVenue("Fillmore Silver Spring", fillDC(), exactIs("The Fillmore Silver Spring", "Silver Spring"));
  await runVenue("The Fillmore, Silver Spring, MD", fillDC(), exactIs("The Fillmore Silver Spring", "Silver Spring"));
  await runVenue("Fillmore, Maryland", fillDC(), exactIs("The Fillmore Silver Spring", "Silver Spring"));

  // Same-named rooms in other cities
  const para = () => [P("Paramount Theatre", "Austin", "Texas", ["Performing arts theater"]), P("Paramount Theatre", "Oakland", "California", ["Performing arts theater"]), P("Paramount Theatre", "Seattle", "Washington", ["Performing arts theater"]), P("The Paramount", "Huntington", "New York")];
  await runVenue("Paramount Theatre, Seattle", para(), exactIs("Paramount Theatre", "Seattle"));
  await runVenue("Paramount Theater Seattle WA", para(), exactIs("Paramount Theatre", "Seattle"));
  await runVenue("The Paramount, Huntington NY", para(), exactIs("The Paramount", "Huntington"));
  await runVenue("Paramount, Oakland", para(), exactIs("Paramount Theatre", "Oakland"));
  await runVenue("Paramount Theatre, Denver", para(), (o) => !o.includes("exact"), "typed city not in list");
  await runVenue("Paramount Theatre", para(), (o) => o.includes("ambiguous") || o.includes("exact"));
  const orph = () => [P("Orpheum Theatre", "Los Angeles", "California", ["Performing arts theater"]), P("Orpheum Theatre", "Minneapolis", "Minnesota", ["Performing arts theater"]), P("Orpheum Theatre", "Boston", "Massachusetts", ["Performing arts theater"])];
  await runVenue("Orpheum, Minneapolis", orph(), exactIs("Orpheum Theatre", "Minneapolis"));
  await runVenue("Orpheum Theater LA", orph(), exactIs("Orpheum Theatre", "Los Angeles"));
  await runVenue("Orpheum Theatre, Boston, MA", orph(), exactIs("Orpheum Theatre", "Boston"));
  const st = () => [P("State Theatre", "Minneapolis", "Minnesota", ["Performing arts theater"]), P("State Theatre", "Portland", "Maine"), P("Aladdin Theater", "Portland", "Oregon")];
  await runVenue("State Theatre, Portland, ME", st(), exactIs("State Theatre", "Portland"));
  await runVenue("State Theatre Portland Maine", st(), exactIs("State Theatre", "Portland"));
  await runVenue("Aladdin Theater, Portland, OR", st(), exactIs("Aladdin Theater", "Portland"));
  const cont = () => [P("The Continental Club", "Houston", "Texas", ["Bar", "Live music venue"]), P("The Continental Club", "Austin", "Texas", ["Bar", "Live music venue"])];
  await runVenue("Continental Club, Austin", cont(), exactIs("The Continental Club", "Austin"));
  await runVenue("Continental Club Austin TX", cont(), exactIs("The Continental Club", "Austin"));
  await runVenue("Continental Club, Austin, Texas", cont(), exactIs("The Continental Club", "Austin"));
  await runVenue("Continental Club, Texas", cont(), (o) => o.includes("ambiguous"));
  const gran = () => [P("Granada Theater", "Dallas", "Texas"), P("The Granada", "Lawrence", "Kansas"), P("Texas Theatre", "Dallas", "Texas", ["Movie theater", "Performing arts theater"])];
  await runVenue("Granada, Dallas", gran(), exactIs("Granada Theater", "Dallas"));
  await runVenue("The Granada, Lawrence, KS", gran(), exactIs("The Granada", "Lawrence"));
  await runVenue("Granada Theatre Dallas TX", gran(), exactIs("Granada Theater", "Dallas"));
  await runVenue("Granada Lawrence Kansas", gran(), exactIs("The Granada", "Lawrence"));
  await runVenue("Texas Theater, Dallas", gran(), exactIs("Texas Theatre", "Dallas"));
  const blue = () => [P("The Bluebird Cafe", "Nashville", "Tennessee", ["Cafe", "Bar"]), P("Bluebird Theater", "Denver", "Colorado"), P("The Bluebird", "Bloomington", "Indiana", ["Bar"])];
  await runVenue("Bluebird, Denver", blue(), exactIs("Bluebird Theater", "Denver"));
  await runVenue("Bluebird Cafe, Nashville", blue(), exactIs("The Bluebird Cafe", "Nashville"));
  await runVenue("Bluebird Café Nashville TN", blue(), exactIs("The Bluebird Cafe", "Nashville"));
  await runVenue("Bluebird, Bloomington, IN", blue(), exactIs("The Bluebird", "Bloomington"));
  await runVenue("Bluebird Theater", [P("The Bluebird", "Bloomington", "Indiana", ["Bar"]), P("The Bluebird Cafe", "Nashville", "Tennessee", ["Cafe", "Bar"])], (o) => !o.includes("exact"), "Denver room missing: not exact");
  await runVenue("Bluebird Theatre, Denver", [P("Bluebird Theater", "Denver", "Colorado"), P("The Bluebird Cafe", "Nashville", "Tennessee", ["Cafe", "Bar"])], exactIs("Bluebird Theater", "Denver"));

  // Rooms named after their city
  const chi = () => [P("Chicago Theatre", "Chicago", "Illinois", ["Performing arts theater"]), P("Thalia Hall", "Chicago", "Illinois"), P("Metro", "Chicago", "Illinois", ["Night club", "Live music venue"])];
  await runVenue("Chicago Theatre, Chicago, IL", chi(), exactIs("Chicago Theatre", "Chicago"));
  await runVenue("The Chicago Theater", chi(), exactIs("Chicago Theatre", "Chicago"));
  await runVenue("Metro, Chicago", chi(), exactIs("Metro", "Chicago"));
  await runVenue("Metro Chicago", chi(), exactIs("Metro", "Chicago"));
  await runVenue("Thalia Hall, Chicago IL 60608", chi(), exactIs("Thalia Hall", "Chicago"));
  await runVenue("Nashville Palace, Nashville, TN", [P("Nashville Palace", "Nashville", "Tennessee", ["Bar", "Live music venue"]), P("Ryman Auditorium", "Nashville", "Tennessee", ["Concert hall"])], exactIs("Nashville Palace", "Nashville"));
  await runVenue("Ryman, Nashville", [P("Nashville Palace", "Nashville", "Tennessee", ["Bar", "Live music venue"]), P("Ryman Auditorium", "Nashville", "Tennessee", ["Concert hall"])], exactIs("Ryman Auditorium", "Nashville"));
  await runVenue("The Ryman", [P("Ryman Auditorium", "Nashville", "Tennessee", ["Concert hall"])], exactIs("Ryman Auditorium", "Nashville"));
  await runVenue("Hollywood Palladium, Los Angeles", [P("Hard Rock Live", "Hollywood", "Florida", ["Concert hall"]), P("Hollywood Palladium", "Los Angeles", "California", ["Concert hall"])], exactIs("Hollywood Palladium", "Los Angeles"));
  await runVenue("Palladium, Hollywood", [P("Hard Rock Live", "Hollywood", "Florida", ["Concert hall"]), P("Hollywood Palladium", "Los Angeles", "California", ["Concert hall"])], notExactWrong("Hollywood Palladium", "Los Angeles"));
  await runVenue("Hollywood Palladium", [P("Hard Rock Live", "Hollywood", "Florida", ["Concert hall"]), P("Hollywood Palladium", "Los Angeles", "California", ["Concert hall"])], exactIs("Hollywood Palladium", "Los Angeles"));
  await runVenue("Asbury Lanes, Asbury Park, NJ", [P("The Stone Pony", "Asbury Park", "New Jersey", ["Bar", "Live music venue"]), P("Asbury Lanes", "Asbury Park", "New Jersey")], exactIs("Asbury Lanes", "Asbury Park"));
  await runVenue("Stone Pony, Asbury Park", [P("The Stone Pony", "Asbury Park", "New Jersey", ["Bar", "Live music venue"]), P("Asbury Lanes", "Asbury Park", "New Jersey")], exactIs("The Stone Pony", "Asbury Park"));
  await runVenue("Kansas City Music Hall, Kansas City, MO", [P("Kansas City Live!", "Kansas City", "Missouri"), P("Kansas City Music Hall", "Kansas City", "Missouri", ["Concert hall"])], exactIs("Kansas City Music Hall", "Kansas City"));
  await runVenue("Music Hall, Kansas City", [P("Kansas City Live!", "Kansas City", "Missouri"), P("Kansas City Music Hall", "Kansas City", "Missouri", ["Concert hall"])], exactIs("Kansas City Music Hall", "Kansas City"));
  await runVenue("Austin City Limits Live, Austin", [P("ACL Live at The Moody Theater", "Austin", "Texas", ["Concert hall"]), P("Mohawk Austin", "Austin", "Texas", ["Bar", "Live music venue"])], (o) => o.startsWith("ACL Live") || o === "none");
  await runVenue("Moody Theater, Austin", [P("ACL Live at The Moody Theater", "Austin", "Texas", ["Concert hall"]), P("Mohawk Austin", "Austin", "Texas", ["Bar", "Live music venue"])], (o) => o.startsWith("ACL Live"));
  // Mohawk family
  const mohawk = () => [P("Mohawk", "Mohawk", "New York", ["Bar"]), P("Mohawk Austin", "Austin", "Texas", ["Bar", "Live music venue"])];
  await runVenue("Mohawk, Austin, TX", mohawk(), exactIs("Mohawk Austin", "Austin"));
  await runVenue("Mohawk ATX", mohawk(), exactIs("Mohawk Austin", "Austin"));
  await runVenue("The Mohawk Austin Texas", mohawk(), exactIs("Mohawk Austin", "Austin"));
  await runVenue("Mohawk, Mohawk NY", mohawk(), exactIs("Mohawk", "Mohawk"));
  await runVenue("Mohawk", mohawk(), (o) => o.startsWith("Mohawk Austin [Austin] ambiguous"));
  await runVenue("Mohawk Bar Austin", mohawk(), exactIs("Mohawk Austin", "Austin"));
  await runVenue("Antones, Austin", [P("Antone's Nightclub", "Austin", "Texas", ["Night club", "Live music venue"])], exactIs("Antone's Nightclub", "Austin"));
  await runVenue("Antone's Nightclub Austin TX 78701", [P("Antone's Nightclub", "Austin", "Texas", ["Night club", "Live music venue"])], exactIs("Antone's Nightclub", "Austin"));
  await runVenue("Antone's", [P("Antone's Nightclub", "Austin", "Texas", ["Night club", "Live music venue"]), P("Antone's Record Shop", "Austin", "Texas", ["Record store", "Live music venue"])], exactIs("Antone's Nightclub", "Austin"));
  // Punctuation and initials
  await runVenue("Hi Dive, Denver", [P("Hi-Dive", "Denver", "Colorado", ["Bar", "Live music venue"])], exactIs("Hi-Dive", "Denver"));
  await runVenue("HiDive Denver CO", [P("Hi-Dive", "Denver", "Colorado", ["Bar", "Live music venue"])], exactIs("Hi-Dive", "Denver"));
  await runVenue("House of Blues - Chicago", [P("House of Blues Houston", "Houston", "Texas"), P("House of Blues Chicago", "Chicago", "Illinois")], exactIs("House of Blues Chicago", "Chicago"));
  await runVenue("House of Blues (Chicago)", [P("House of Blues Houston", "Houston", "Texas"), P("House of Blues Chicago", "Chicago", "Illinois")], exactIs("House of Blues Chicago", "Chicago"));
  await runVenue("House of Blues Chicago Illinois", [P("House of Blues Houston", "Houston", "Texas"), P("House of Blues Chicago", "Chicago", "Illinois")], exactIs("House of Blues Chicago", "Chicago"));
  await runVenue("House of Blues at Chicago", [P("House of Blues Houston", "Houston", "Texas"), P("House of Blues Chicago", "Chicago", "Illinois")], exactIs("House of Blues Chicago", "Chicago"));
  await runVenue("HOB Chicago", [P("House of Blues Houston", "Houston", "Texas"), P("House of Blues Chicago", "Chicago", "Illinois")], (o) => o === "none" || o.startsWith("House of Blues Chicago"));
  await runVenue("9:30 Club, DC", [P("9:30 Club", "Washington", "District of Columbia")], exactIs("9:30 Club", "Washington"));
  await runVenue("930 Club Washington, D.C.", [P("9:30 Club", "Washington", "District of Columbia")], exactIs("9:30 Club", "Washington"));
  await runVenue("The 9:30 Club in Washington DC", [P("9:30 Club", "Washington", "District of Columbia")], exactIs("9:30 Club", "Washington"));
  await runVenue("Union Transfer Philly", [P("Union Transfer", "Philadelphia", "Pennsylvania")], exactIs("Union Transfer", "Philadelphia"));
  await runVenue("Union Transfer, Philadelphia, PA 19123", [P("Union Transfer", "Philadelphia", "Pennsylvania")], exactIs("Union Transfer", "Philadelphia"));
  await runVenue("Exit/In Nashville", [P("Exit/In", "Nashville", "Tennessee")], exactIs("Exit/In", "Nashville"));
  await runVenue("Johnny Brenda's, Philadelphia, PA", [P("Johnny Brenda's", "Philadelphia", "Pennsylvania")], exactIs("Johnny Brenda's", "Philadelphia"));
  await runVenue("Doug Fir, PDX", [P("Doug Fir Lounge", "Portland", "Oregon", ["Bar", "Live music venue"])], exactIs("Doug Fir Lounge", "Portland"));
  await runVenue("Doug Fir Lounge, Portland, Ore.", [P("Doug Fir Lounge", "Portland", "Oregon", ["Bar", "Live music venue"])], exactIs("Doug Fir Lounge", "Portland"));
  await runVenue("First Avenue, Minneapolis", [P("7th St Entry", "Minneapolis", "Minnesota"), P("First Avenue", "Minneapolis", "Minnesota", ["Night club", "Live music venue"])], exactIs("First Avenue", "Minneapolis"));
  await runVenue("First Ave, Minneapolis", [P("7th St Entry", "Minneapolis", "Minnesota"), P("First Avenue", "Minneapolis", "Minnesota", ["Night club", "Live music venue"])], notExactWrong("First Avenue", "Minneapolis"));
  await runVenue("Basement East", [P("The Basement East", "Nashville", "Tennessee"), P("The Basement", "Nashville", "Tennessee")], exactIs("The Basement East", "Nashville"));
  await runVenue("The Basement, Nashville TN", [P("The Basement East", "Nashville", "Tennessee"), P("The Basement", "Nashville", "Tennessee")], exactIs("The Basement", "Nashville"));
  await runVenue("Emtpy Bottle, Chicago", [P("The Empty Bottle", "Chicago", "Illinois", ["Bar", "Live music venue"])], notExactWrong("The Empty Bottle", "Chicago"));
  await runVenue("Empty Bottle, Chi", [P("The Empty Bottle", "Chicago", "Illinois", ["Bar", "Live music venue"])], exactIs("The Empty Bottle", "Chicago"));
  await runVenue("Empty Bottle, Chicgo", [P("The Empty Bottle", "Chicago", "Illinois", ["Bar", "Live music venue"])], notExactWrong("The Empty Bottle", "Chicago"));
  await runVenue("Empty Bottle", [P("The Empty Bottle", "Chicago", "Illinois", ["Bar", "Live music venue"]), P("Empty Bottle Brewing", "Chicago", "Illinois", ["Bar"])], exactIs("The Empty Bottle", "Chicago"));
  await runVenue("Club Congress, Tucson", [P("Hotel Congress", "Tucson", "Arizona", ["Hotel", "Bar"]), P("Club Congress", "Tucson", "Arizona", ["Night club", "Live music venue"])], exactIs("Club Congress", "Tucson"));
  await runVenue("Hotel Congress, Tucson", [P("Hotel Congress", "Tucson", "Arizona", ["Hotel", "Bar"]), P("Club Congress", "Tucson", "Arizona", ["Night club", "Live music venue"])], exactIs("Hotel Congress", "Tucson"));
  await runVenue("Fox Theatre, Tucson", [P("Fox Theatre", "Atlanta", "Georgia"), P("Fox Tucson Theatre", "Tucson", "Arizona")], exactIs("Fox Tucson Theatre", "Tucson"), "suite");
  await runVenue("Fox Theatre, Atlanta", [P("Fox Theatre", "Atlanta", "Georgia"), P("Fox Tucson Theatre", "Tucson", "Arizona")], exactIs("Fox Theatre", "Atlanta"));
  await runVenue("Fox Theatre Atlanta GA", [P("Fox Tucson Theatre", "Tucson", "Arizona"), P("Fox Theatre", "Atlanta", "Georgia")], exactIs("Fox Theatre", "Atlanta"));
  await runVenue("The Fox, Oakland", [P("Fox Theatre", "Atlanta", "Georgia"), P("Fox Oakland Theatre", "Oakland", "California")], notExactWrong("Fox Oakland Theatre", "Oakland"));
  await runVenue("Crystal Ballroom, Portland", [P("Crystal Ballroom", "Somerville", "Massachusetts"), P("Crystal Ballroom", "Portland", "Oregon")], exactIs("Crystal Ballroom", "Portland"));
  await runVenue("Crystal Ballroom, Boston", [P("Crystal Ballroom", "Portland", "Oregon"), P("Crystal Ballroom", "Somerville", "Massachusetts")], (o) => !o.includes("exact"));
  await runVenue("Crystal Ballroom, Somerville, MA", [P("Crystal Ballroom", "Portland", "Oregon"), P("Crystal Ballroom", "Somerville", "Massachusetts")], exactIs("Crystal Ballroom", "Somerville"));
  // Non-US
  const uk = (name, city, region, cats = ["Live music venue"]) => ({ ...P(name, city, region, cats), country: "United Kingdom", countryCode: "GB" });
  await runVenue("Brudenell Social Club, Leeds", [uk("Brudenell Social Club", "Leeds", "England")], exactIs("Brudenell Social Club", "Leeds"));
  await runVenue("Rock City, Nottingham, UK", [P("The Rock", "San Antonio", "Texas", ["Bar"]), uk("Rock City", "Nottingham", "England")], exactIs("Rock City", "Nottingham"));
  await runVenue("The Lexington, London", [uk("The Lexington", "London", "England", ["Pub", "Live music venue"]), P("Lexington Theatre", "Lexington", "Kentucky", ["Performing arts theater"])], exactIs("The Lexington", "London"));
  await runVenue("Lexington, London", [P("Lexington Theatre", "Lexington", "Kentucky", ["Performing arts theater"]), uk("The Lexington", "London", "England", ["Pub", "Live music venue"])], exactIs("The Lexington", "London"));
  await runVenue("Lexington Theatre, Lexington, KY", [uk("The Lexington", "London", "England", ["Pub", "Live music venue"]), P("Lexington Theatre", "Lexington", "Kentucky", ["Performing arts theater"])], exactIs("Lexington Theatre", "Lexington"));
  await runVenue("The Lexington", [P("Lexington Theatre", "Lexington", "Kentucky", ["Performing arts theater"]), uk("The Lexington", "London", "England", ["Pub", "Live music venue"])], exactIs("The Lexington", "London"));
  await runVenue("Paradiso Amsterdam", [{ ...P("Paradiso", "Amsterdam", "North Holland"), country: "Netherlands", countryCode: "NL" }], exactIs("Paradiso", "Amsterdam"));
  await runVenue("Lee's Palace, Toronto, ON", [{ ...P("Lee's Palace", "Toronto", "Ontario"), country: "Canada", countryCode: "CA" }], exactIs("Lee's Palace", "Toronto"));
  await runVenue("Horseshoe Tavern Toronto", [{ ...P("Horseshoe Tavern", "Toronto", "Ontario", ["Bar", "Live music venue"]), country: "Canada", countryCode: "CA" }], exactIs("Horseshoe Tavern", "Toronto"));
  await runVenue("The Horseshoe, Toronto", [{ ...P("Horseshoe Tavern", "Toronto", "Ontario", ["Bar", "Live music venue"]), country: "Canada", countryCode: "CA" }], exactIs("Horseshoe Tavern", "Toronto"));

  // ---------- artists ----------
  const A = (names, genre) => names.map((x) => art(x, genre));
  const aIs = (name, ...m) => (o) => m.some((x) => o === `${name} ${x}`);
  await runArtist("Wild Child", A(["Wild Child", "Wildchild"]), aIs("Wild Child", "exact"));
  await runArtist("Wildchild", A(["Wild Child", "Wildchild"]), aIs("Wildchild", "exact"));
  await runArtist("Wild Child", A(["Wildchild", "Wild Nothing", "Child Bite"]), (o) => !o.includes("exact"), "only the space-free namesake found");
  await runArtist("Ice Age", A(["Iceage", "Ice Cube", "Age of Ice"]), (o) => !o.includes("exact"), "only the space-free namesake found");
  await runArtist("Night Moves", A(["Nightmoves", "Night Beats"]), (o) => !o.includes("exact"), "only the space-free namesake found");
  await runArtist("S. G. Goodman", A(["S N U G", "S.G. Goodman"]), aIs("S.G. Goodman", "exact"));
  await runArtist("SG Goodman", A(["S.G. Goodman", "S N U G"]), aIs("S.G. Goodman", "exact", "closest"));
  await runArtist("J. J. Cale", A(["alt-J", "J.J. Cale"]), aIs("J.J. Cale", "exact"));
  await runArtist("JJ Cale", A(["J.J. Cale", "alt-J"]), aIs("J.J. Cale", "exact", "closest"));
  await runArtist("Snail Male", A(["Snail Mail", "Male Bonding"]), aIs("Snail Mail", "closest"));
  await runArtist("Beyonce", A(["Beyoncé"]), aIs("Beyoncé", "exact"));
  await runArtist("Bjork", A(["Björk"]), aIs("Björk", "exact"));
  await runArtist("Sigur Ros", A(["Sigur Rós"]), aIs("Sigur Rós", "exact"));
  await runArtist("MO", A(["MØ", "Mo Troper", "Mos Def"]), (o) => o.startsWith("MØ ") || o === "none", "Ø doesn't fold");
  await runArtist("Royksopp", A(["Röyksopp"]), aIs("Röyksopp", "exact"));
  await runArtist("Keb Mo", A(["Keb' Mo'"], "Blues"), aIs("Keb' Mo'", "exact"));
  await runArtist("Keb' Mo'", A(["Keb' Mo'"], "Blues"), aIs("Keb' Mo'", "exact"));
  await runArtist("Kingfish", A(["Kingfish", "Christone \"Kingfish\" Ingram"], "Blues"), aIs("Kingfish", "exact"));
  await runArtist("Christone Kingfish Ingram", A(["Kingfish", "Christone \"Kingfish\" Ingram"], "Blues"), aIs("Christone \"Kingfish\" Ingram", "exact"));
  await runArtist("Nobody Real Band Xyz", A(["The Band", "Band of Horses"]), is("none"));
  await runArtist("Gary Clark", A(["Gary Clark Jr."], "Blues"), aIs("Gary Clark Jr.", "closest"));
  await runArtist("Gary Clark Jr", A(["Gary Clark Jr."], "Blues"), aIs("Gary Clark Jr.", "exact"));
  await runArtist("Bea", A(["Beach House"]), is("none"));
  await runArtist("Tyler the Creator", A(["Tyler, The Creator", "Tyler Childers"]), aIs("Tyler, The Creator", "exact"));
  await runArtist("Simon and Garfunkel", A(["Simon & Garfunkel"]), aIs("Simon & Garfunkel", "exact"));
  await runArtist("Florence and the Machine", A(["Florence + the Machine"]), aIs("Florence + the Machine", "exact"));
  await runArtist("Guns and Roses", A(["Guns N' Roses"]), aIs("Guns N' Roses", "closest", "exact"));
  await runArtist("ACDC", A(["AC/DC"]), aIs("AC/DC", "exact", "closest"));
  await runArtist("AC DC", A(["AC/DC"]), aIs("AC/DC", "exact"));
  await runArtist("Iceage", A(["Ice Age", "Iceage"]), aIs("Iceage", "exact"));
  await runArtist("Hippo Campus", A(["Hippocampus", "Hippo Campus"]), aIs("Hippo Campus", "exact"));
  await runArtist("Charley Crocket", A(["Charley Crockett"], "Country"), aIs("Charley Crockett", "closest"));
  await runArtist("Wednesday", A(["Wednesday", "Wednesday 13", "Wednesday Campanella"]), aIs("Wednesday", "exact"));
  await runArtist("Black Country New Road", A(["Black Country, New Road"]), aIs("Black Country, New Road", "exact"));
  await runArtist("St Vincent", A(["St. Vincent"]), aIs("St. Vincent", "exact"));
  await runArtist("The War on Drugs", A(["The War On Drugs", "War"]), aIs("The War On Drugs", "exact"));
  await runArtist("The The", A(["The The", "The Who"]), aIs("The The", "exact"));
  await runArtist("!!!", A(["!!!", "Chk Chk Chk"]), (o) => o.startsWith("!!! "));
  await runArtist("Chk Chk Chk", A(["!!!"]), (o) => true);
  await runArtist("The Band", A(["The Band", "Band of Horses", "The Band Camino"]), aIs("The Band", "exact"));
  await runArtist("Band Camino", A(["The Band", "The Band Camino"]), aIs("The Band Camino", "exact"));
  await runArtist("Tedeschi Trucks", A(["Tedeschi Trucks Band", "Derek Trucks"], "Blues"), aIs("Tedeschi Trucks Band", "closest"));
  await runArtist("Doyle Bramhall", A(["Doyle Bramhall II", "Doyle Bramhall"], "Blues"), aIs("Doyle Bramhall", "exact"));
  await runArtist("Doyle Bramhall II", A(["Doyle Bramhall", "Doyle Bramhall II"], "Blues"), aIs("Doyle Bramhall II", "exact"));
  await runArtist("Sue Foley", A(["Sue Foley"], "Blues"), aIs("Sue Foley", "exact"));
  await runArtist("King Gizzard", A(["King Gizzard & The Lizard Wizard"]), aIs("King Gizzard & The Lizard Wizard", "closest"));
  await runArtist("KGLW", A(["King Gizzard & The Lizard Wizard"]), (o) => true);
  await runArtist("Lizzo", A(["Lizzo", "Lizzy McAlpine"]), aIs("Lizzo", "exact"));
  await runArtist("Mt. Joy", A(["Mt. Joy", "Mount Joy"]), aIs("Mt. Joy", "exact"));
  await runArtist("Mt Joy", A(["Mt. Joy"]), aIs("Mt. Joy", "exact"));
  await runArtist("Sylvan Esso", A(["Sylvan Esso"]), aIs("Sylvan Esso", "exact"));
  await runArtist("Big Thief", A(["Big Thief", "Thief"]), aIs("Big Thief", "exact"));
  await runArtist("Boygenius", A(["boygenius"]), aIs("boygenius", "exact"));
  await runArtist("boy genius", A(["boygenius", "Boy Genius Report"]), aIs("boygenius", "exact", "closest"));
  await runArtist("Mac DeMarco", A(["Mac DeMarco"]), aIs("Mac DeMarco", "exact"));
  await runArtist("Mac De Marco", A(["Mac DeMarco"]), aIs("Mac DeMarco", "exact", "closest"));
  await runArtist("Of Montreal", A(["of Montreal", "Montreal"]), aIs("of Montreal", "exact"));
  await runArtist("Montreal", A(["of Montreal", "Montreal"]), aIs("Montreal", "exact"));
  await runArtist("A Tribe Called Quest", A(["A Tribe Called Quest", "Tribe"]), aIs("A Tribe Called Quest", "exact"));
  await runArtist("The Who", A(["The Who", "Who Is Fancy"]), aIs("The Who", "exact"));
  await runArtist("Who", A(["The Who", "Who Is Fancy"]), aIs("The Who", "exact"));
  await runArtist("Japanese Breakfast", A(["Japanese Breakfast"]), aIs("Japanese Breakfast", "exact"));
  await runArtist("Japanese Brekfast", A(["Japanese Breakfast", "Japanese House"]), aIs("Japanese Breakfast", "closest"));
  await runArtist("The Japanese House", A(["Japanese Breakfast", "The Japanese House"]), aIs("The Japanese House", "exact"));
  await runArtist("Turnpike Troubadors", A(["Turnpike Troubadours"], "Country"), aIs("Turnpike Troubadours", "closest"));
  await runArtist("Kurt Vile and the Violators", A(["Kurt Vile", "Kurt Vile & The Violators"]), aIs("Kurt Vile & The Violators", "exact"));
  await runArtist("Kurt Vile", A(["Kurt Vile & The Violators", "Kurt Vile"]), aIs("Kurt Vile", "exact"));
  await runArtist("Prince", A(["Prince", "Prince Royce", "Prince Daddy & The Hyena"]), aIs("Prince", "exact"));
  await runArtist("Pr1nce", A(["Prince"]), (o) => true);
  await runArtist("Run The Jewels", A(["Run the Jewels"]), aIs("Run the Jewels", "exact"));
  await runArtist("RTJ", A(["Run the Jewels", "RTJ"]), aIs("RTJ", "exact"));
  await runArtist("M83", A(["M83"]), aIs("M83", "exact"));
  await runArtist("M 83", A(["M83"]), aIs("M83", "exact", "closest"));
  await runArtist("Sleater Kinney", A(["Sleater-Kinney"]), aIs("Sleater-Kinney", "exact"));
  await runArtist("SleaterKinney", A(["Sleater-Kinney"]), aIs("Sleater-Kinney", "exact", "closest"));
  await runArtist("Rufus Du Sol", A(["RÜFÜS DU SOL"]), aIs("RÜFÜS DU SOL", "exact"));
  await runArtist("Rufus", A(["RÜFÜS DU SOL", "Rufus Wainwright", "Rufus"]), aIs("Rufus", "exact"));
  await runArtist("Blink 182", A(["blink-182"]), aIs("blink-182", "exact"));
  await runArtist("Blink-182", A(["blink-182", "Blink"]), aIs("blink-182", "exact"));
  await runArtist("blink182", A(["blink-182", "Blink"]), aIs("blink-182", "exact", "closest"));
  await runArtist("Twenty One Pilots", A(["twenty one pilots", "21 Pilots"]), aIs("twenty one pilots", "exact"));
  await runArtist("Alt J", A(["alt-J", "J.J. Cale"]), aIs("alt-J", "exact"));
  await runArtist("altj", A(["alt-J", "J.J. Cale"]), aIs("alt-J", "exact", "closest"));

  // ---------- splitting ----------
  await runSplit("Wednesday, Snail Mail", eqList("Wednesday", "Snail Mail"));
  await runSplit('"Tyler, the Creator", Wednesday', eqList("Tyler, the Creator", "Wednesday"));
  await runSplit("Simon and Garfunkel; Wednesday", eqList("Simon and Garfunkel", "Wednesday"));
  await runSplit("Guns N' Roses, Wednesday", eqList("Guns N' Roses", "Wednesday"));
  await runSplit("Keb' Mo', Kingfish", eqList("Keb' Mo'", "Kingfish"));
  await runSplit("Kingfish, Keb' Mo'", eqList("Kingfish", "Keb' Mo'"));
  await runSplit("'Til Tuesday, Wednesday", eqList("'Til Tuesday", "Wednesday"));
  await runSplit("'Til Tuesday, Keb' Mo'", eqList("'Til Tuesday", "Keb' Mo'"));
  await runSplit("'Til Tuesday, Wednesday, Keb' Mo'", eqList("'Til Tuesday", "Wednesday", "Keb' Mo'"));
  await runSplit("‘Til Tuesday, Wednesday, Keb’ Mo’", eqList("‘Til Tuesday", "Wednesday", "Keb’ Mo’"));
  await runSplit("Wednesday\n'68\nKeb' Mo'", eqList("Wednesday", "'68", "Keb' Mo'"));
  await runSplit("Wednesday, 'Til Tuesday, Kingfish", eqList("Wednesday", "'Til Tuesday", "Kingfish"));
  await runSplit('Wednesday; "Black Country, New Road"', eqList("Wednesday", "Black Country, New Road"));
  await runSplit("“Black Country, New Road”, Wednesday", eqList("Black Country, New Road", "Wednesday"));
  await runSplit("„Black Country, New Road“, Wednesday", eqList("Black Country, New Road", "Wednesday"));
  await runSplit("«Black Country, New Road», Wednesday", eqList("Black Country, New Road", "Wednesday"));
  await runSplit("'Black Country, New Road', Wednesday", eqList("Black Country, New Road", "Wednesday"));
  await runSplit("‘Black Country, New Road’, Wednesday", eqList("Black Country, New Road", "Wednesday"));
  await runSplit("Antone’s Allstars, Wednesday", eqList("Antone’s Allstars", "Wednesday"));
  await runSplit('Wednesday, "Weird Al" Yankovic', (o) => JSON.parse(o).length === 2);
  await runSplit("'Weird Al' Yankovic, Wednesday", (o) => JSON.parse(o).length === 2);
  await runSplit('"Earth, Wind & Fire", Wednesday', eqList("Earth, Wind & Fire", "Wednesday"));
  await runSplit('Wednesday, "Snail Mail, Dehd', eqList("Wednesday", "Snail Mail", "Dehd"));
  await runSplit("'Tyler, the Creator', Keb' Mo'", eqList("Tyler, the Creator", "Keb' Mo'"));
  await runSplit("‘68, \"Tyler, the Creator\"", eqList("‘68", "Tyler, the Creator"));
  await runSplit("The B-52's, 'Til Tuesday", eqList("The B-52's", "'Til Tuesday"));
  await runSplit("'Til Tuesday, The B-52's", eqList("'Til Tuesday", "The B-52's"));
  await runSplit("Rock 'n' Roll Soldiers, Wednesday", eqList("Rock 'n' Roll Soldiers", "Wednesday"));
  await runSplit("'N Sync, Wednesday, Keb' Mo'", eqList("'N Sync", "Wednesday", "Keb' Mo'"));
  await runSplit("Wednesday\nSnail Mail\n\nDehd", eqList("Wednesday", "Snail Mail", "Dehd"));
}
